### ISSUE TITLE
Issue with PyTorch Version in Installation Step

### ISSUE THREAD

**Issue by Zyew** [sypsyp97/Trainable-Fourier-Series#1]
While following the installation instructions for pyronn, I encountered an issue in Step 5:

The current command:

pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

installs the latest version of PyTorch (2.3.1). However, for compatibility reasons, it would be better to install specific versions that are known to work with pyronn.

I suggest updating the command to:

pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 torchaudio==2.0.2+cu118 --index-url https://download.pytorch.org/whl/cu118

This ensures that the correct versions are installed, preventing potential compatibility issues with pyronn.

**Comment by sypsyp97** [comment]
> While following the installation instructions for pyronn, I encountered an issue in Step 5:
> 
> 
> 
> The current command:
> 
> 
> 
> pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> 
> 
> 
> installs the latest version of PyTorch (2.3.1). However, for compatibility reasons, it would be better to install specific versions that are known to work with pyronn.
> 
> 
> 
> I suggest updating the command to:
> 
> 
> 
> pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 torchaudio==2.0.2+cu118 --index-url https://download.pytorch.org/whl/cu118
> 
> 
> 
> This ensures that the correct versions are installed, preventing potential compatibility issues with pyronn.

Thanks, please open a pull request, so that I can close this issue. 😄
