### ISSUE TITLE
ModuleNotFoundError:No module named 'pystencils.interpolation_astnodes'

### ISSUE THREAD

**Issue by LIYINYING100** [sypsyp97/Trainable-Fourier-Series#2]
您好，我下载的版本都是按照environment.yml里面的下的，请问您有遇见这个问题吗？应该怎么解决呀

**Comment by sypsyp97** [comment]
> 您好，我下载的版本都是按照environment.yml里面的下的，请问您有遇见这个问题吗？应该怎么解决呀

你好，最近代码有点改动我还没有更新env文件，晚点我会更新。如果你是用windows话，你可以新建一个conda env，然后python=3.12，安装cuda=11.8，pytorch=2.5.0，h5py，matplotlib还有numpy。最后安装好pyronn/wheel文件夹中对应的whl文件代码就能运行了。

如果是linux的话，请用以下配置：python=3.11，安装cuda=11.8，pytorch=2.1.0，h5py，matplotlib，numpy，最后安装另外一个whl。

有问题随时联系：）

**Comment by LIYINYING100** [comment]
您好，请问pyronn_layers您使用的是哪个版本啊

**Comment by sypsyp97** [comment]
> 您好，请问pyronn_layers您使用的是哪个版本啊

现在已经不需要自己单独安装pyronn layers了

**Comment by sypsyp97** [comment]
> 您好，请问pyronn_layers您使用的是哪个版本啊

我在pyronn文件夹新增了一个自动安装脚本，希望能有帮助

**Comment by LIYINYING100** [comment]
好的，非常感谢，问题已经解决了
