### ISSUE TITLE
Linux下安装问题

### ISSUE THREAD

**Issue by springXIACJ** [sypsyp97/Trainable-Fourier-Series#3]
您好，
我按照您Installation Guide for HPC.md中的Quick Installation一步步的安装，但提示我”ERROR: pyronn-031-cp311-cuda118-torch210-linux_x86_64.whl is not a valid wheel filename.“ 然后， 按照”Build by yourself on HPC“的指示安装，在运行sbatch build.sh时提示sbatch: error: s_p_parse_file: unable to status file /etc/slurm-llnl/slurm.conf: No such file or directory, retrying in 1sec up to 60sec
sbatch: error: ClusterName needs to be specified
sbatch: fatal: Unable to process configuration file。
请问有什么解决方案？

**Comment by sypsyp97** [comment]
你好，第一个问题看着像是路径错误，或许安装wheel之前先cd到存放wheel的文件夹下。第二个问题看着和你们hpc的slurm有关，你可以试着改一下sh文件

**Comment by springXIACJ** [comment]
安装wheel之前是cd到存放wheel的文件夹，但就是无法安装。

**Comment by sypsyp97** [comment]
说这个 wheel is not a valid wheel filename...你重命名试试呢

**Comment by sypsyp97** [comment]
你好，之前报错是wheel命名不符合规范，现在应该没问题了
